In [6]:
import numpy as np
import tensorflow as tf

In [7]:
# N - number of samples
# T - sequence length
# D - number of input features
# M - number of hidden units
# K - number of output units

In [8]:
N = 2
T = 10
D = 3
M = 5
K = 2

X = np.random.randn(N, T, D)

In [9]:
i = tf.keras.layers.Input(shape=(T, D))
h = tf.keras.layers.SimpleRNN(M)(i)
o = tf.keras.layers.Dense(K)(h)

model = tf.keras.models.Model(i, o)
model.compile(optimizer='adam', loss='mse')

In [10]:
y = model.predict(X)
y

array([[ 1.467792 , -0.545199 ],
       [-2.0615668,  0.8141205]], dtype=float32)

In [11]:
model.get_weights()

[array([[-0.64877963, -0.2031948 , -0.79939806,  0.85738415,  0.03319234],
        [ 0.6027042 , -0.03664976,  0.46097606,  0.03987557,  0.13847452],
        [-0.40207383, -0.4220903 ,  0.05192429,  0.38117653, -0.15553921]],
       dtype=float32),
 array([[-0.51863146, -0.16735159,  0.5799345 ,  0.07047468,  0.6014351 ],
        [-0.28143984, -0.17766361,  0.50108624, -0.30075306, -0.7400592 ],
        [ 0.61449873, -0.6257174 ,  0.32928112,  0.349908  , -0.0027227 ],
        [ 0.3848074 , -0.03910118,  0.12694326, -0.86283875,  0.2996484 ],
        [-0.35514438, -0.73985   , -0.536701  , -0.1940484 ,  0.02813728]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.39898455, -0.85201085],
        [ 0.55001974,  0.5666412 ],
        [ 0.87546873, -0.23063368],
        [-0.6118258 , -0.02297676],
        [ 0.60882986,  0.5135362 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [13]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.layers[0].get_weights()

[]

In [20]:
a, b, c = model.layers[1].get_weights()
a.shape, b.shape, c.shape

((3, 5), (5, 5), (5,))

In [21]:
d, e = model.layers[2].get_weights()
d.shape, e.shape

((5, 2), (2,))

In [22]:
Wxh = a
Whh = b
bh = c

Who = d
bo = e

In [39]:
h_last = np.zeros(M)
y_hat = []

for t in range(T):
    h = np.tanh(X[:, t, :].dot(Wxh) + h_last.dot(Whh) + bh)
    y = h.dot(Who) + bo
    y_hat.append(y)
    
print(y_hat[-1])

[[ 1.00362418 -0.23624566]
 [-2.18546582  0.65132706]]


In [32]:
one_time_step_input = X[:, 1, :]

print(one_time_step_input)

print()

print(one_time_step_input.shape)

[[ 0.52788606  1.20597272 -0.89763457]
 [ 1.75151164  1.29109194 -0.20766758]]

(2, 3)


In [41]:
np.array(y_hat).shape

(10, 2, 2)